// eslint-disable-next-line import/prefer-default-export
export const RegistrationConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
};

export const ArticleConstants = {
  ARTICLE_REQUEST: 'SAVE_ARTICLE_REQUEST',
  ARTICLE_SUCCESS: 'SAVE_ARTICLE_SUCCESS',
  ARTICLE_FAILURE: 'SAVE_ARTICLE_FAILURE',
  ARTICLE_DELETE_REQUEST: 'DELETE_ARTICLE_REQUEST',
  ARTICLE_DELETE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  ARTICLE_DELETE_FAILURE: 'DELETE_ARTICLE_FAILURE',
};
