export const RegistrationConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
};

export const ArticleConstants = {
  ARTICLE_REQUEST: 'SAVE_ARTICLE_REQUEST',
  ARTICLE_SUCCESS: 'SAVE_ARTICLE_SUCCESS',
  ARTICLE_FAILURE: 'SAVE_ARTICLE_FAILURE',
  ARTICLE_DELETE_REQUEST: 'DELETE_ARTICLE_REQUEST',
  ARTICLE_DELETE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  ARTICLE_DELETE_FAILURE: 'DELETE_ARTICLE_FAILURE',
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FETCH_AN_ARTICLE: 'FETCH_AN_ARTICLE',
  ARTICLE_FETCH_NOT_FOUND: 'ARTICLE_FETCH_NOT_FOUND',
  FETCHING_ARTICLE: 'FETCHING_ARTICLE',
  FETCHING_ARTICLEs_IN_PROGRESS: 'FETCHING_ARTICLEs_IN_PROGRESS',
  ARTICLE_LIKING_SUCCESS: 'LIKING_ARTICLE_SUCCESS',
  ARTICLE_LIKING_FAILURE: 'LIKING_ARTICLE_FAILURE',
  ARTICLE_DISLIKING_SUCCESS: 'DISLIKING_ARTICLE_SUCCESS',
  ARTICLE_DISLIKING_FAILURE: 'DISLIKING_ARTICLE_FAILURE',
  ARTICLE_REPORT_SUCCESS: 'ARTICLE_REPORT_SUCCESS',
  ARTICLE_REPORT_FAIL: 'ARTICLE_REPORT_FAIL',
};

export const LoginConstants = {
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
  USER_IS_LOGGING_IN: 'USER_IS_LOGGING_IN',
};

export const profileActionTypes = {
  VIEW_PROFILE_REQUEST: 'USER_VIEW_PROFILE_REQUEST',
  VIEW_PROFILE_SUCCESS: 'USER_VIEW_PROFILE_SUCCESS',
  VIEW_PROFILE_FAILED: 'USER_VIEW_PROFILE_FAILURE',
  EDIT_PROFILE_SUCCESS: 'USER_EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILED: 'USER_EDIT_PROFILE_FAILURE',
  FETCH_FOLLOWING_PROFILES: 'FETCH_FOLLOWING_PROFILES',
  VIEW_AUTHOR_PROFILE_SUCCESS: 'VIEW_AUTHOR_PROFILE_SUCCESS',
};

export const followActionTypes = {
  FOLLOW_AUTHOR_FAIL: 'FOLLOW_AUTHOR_FAIL',
  FOLLOW_AUTHOR_SUCCESS: 'FOLLOW_AUTHOR_SUCCESS',
  UNFOLLOW_AUTHOR_FAILURE: 'UNFOLLOW_AUTHOR_FAIL',
  UNFOLLOW_AUTHOR_SUCCESS: 'UNFOLLOW_AUTHOR_SUCCESS',
};
