// eslint-disable-next-line import/prefer-default-export
export const RegistrationConstants = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
};
export const IS_SUBMITTING_RESET_PASSWORD = 'IS_SUBMITTING_RESET_PASSWORD';
export const SUBMITTING_RESET_PASSWORD_SUCCESS = 'SUBMITTING_RESET_PASSWORD_SUCCESS';
export const SUBMITTING_RESET_PASSWORD_FAIL = 'SUBMITTING_RESET_PASSWORD_FAIL';
